name: nerisraknet
description: ğŸ–¥ï¸ RakNet implementation for NerisMC
version: 1.0.0
repository: https://github.com/NerisMC/NerisRakNet

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
